export default [
	{
		name: "thermal",
		type: "icon",
		requiresAnswer: [],
		questionText: "Would you prefer to be?",
		questionSecondText: "",
		iconText: ["Cooler", "Warmer", "No change"],
		iconColors: ["fb-cyan", "fb-orange", "fb-green"],
		iconImages: [
			"images/icons/prefer_cold.png",
			"images/icons/prefer_warmer.png",
			"images/icons/comfy.png",
		],
	},
	{
		name: "air",
		type: "icon",
		requiresAnswer: [],
		questionText: "Would you prefer to be?",
		questionSecondText: "",
		iconText: ["More air", "Less air", "No change"],
		iconColors: ["fb-cyan", "fb-orange", "fb-green"],
		iconImages: [
			"images/icons/air/air_less_air.png",
			"images/icons/air/air_more_air.png",
			"images/icons/comfy.png",
		],
	},
	{
		name: "freshair",
		type: "icon",
		requiresAnswer: [],
		questionText: "Would you prefer to be?",
		questionSecondText: "",
		iconText: ["Fresh air", "No change", " "],
		iconColors: ["fb-cyan", "fb-green", "fb-black"],
		iconImages: [
			"images/icons/air/air_less_air.png",
			"images/icons/comfy.png",
			"images/icons/comfy.png",
		],
	},
	{
		name: "light",
		type: "icon",
		requiresAnswer: [],
		questionText: "Light preference",
		questionSecondText: "",
		iconText: ["Dimmer", "Brighter", "No Change"],
		iconColors: ["fb-blue", "fb-peach", "fb-green"],
		iconImages: [
			"images/icons/prefer_dimmer.png",
			"images/icons/prefer_brighter.png",
			"images/icons/neutral.png",
		],
	},
	{
		name: "noise",
		type: "icon",
		requiresAnswer: [],
		questionText: "Sound preference",
		questionSecondText: "",
		iconText: ["Quiter", "Louder", "No Change"],
		iconColors: ["fb-orange", "fb-purple", "fb-green"],
		iconImages: [
			"images/icons/prefer_quieter.png",
			"images/icons/prefer_louder.png",
			"images/icons/neutral.png",
		],
	},
	{
		name: "clothing",
		type: "icon",
		requiresAnswer: [],
		questionText: "What are you wearing?",
		questionSecondText: "",
		iconText: ["Light", "Heavy", "Medium"],
		iconColors: ["#6decb9", "#42dee1", "#3fc5f0"],
		iconImages: [
			"images/icons/clothing/light.png",
			"images/icons/clothing/heavy.png",
			"images/icons/clothing/medium.png",
		],
	},
	{
		name: "indoorOutdoor",
		type: "icon",
		requiresAnswer: [],
		questionText: "Are you?",
		questionSecondText: "",
		iconText: ["Indoor", "Outdoor"],
		iconColors: ["fb-peach", "fb-peach"],
		iconImages: [
			"images/icons/outdoor.png",
			"images/icons/indoor.png",
		],
	},
	{
		name: "location",
		type: "icon",
		requiresAnswer: [],
		questionText: "Where are you?",
		questionSecondText: "",
		iconText: ["MeetingR", "Office", "Cafeteria"],
		iconColors: ["fb-peach", "fb-peach", "fb-peach"],
		iconImages: [
			"images/icons/room/meeting.png",
			"images/icons/room/office.png",
			"images/icons/room/lunch.png",
		],
	},
];
